// Inject Sahibe content script logic to show damage badges on search results
// Source adapted from the user's other extension
(function(){
  try {
    // The original file uses chrome.* APIs; keep them as-is
  } catch(e) {}
})();

console.log("Sahibinden Ad Enhancer (merged) loaded.");

// --- View Strategies ---
const viewStrategies={list:{id:"list",adRowSelector:'#searchResultsTable tbody tr[data-id]',adContainerSelector:'#searchResultsTable tbody',imgSelector:'.searchResultsLargeThumbnail img',titleSelector:'a.classifiedTitle',badgeContainer:e=>e.querySelector('td:first-child'),priceCell:e=>e.closest('td')},gallery:{id:"gallery",adRowSelector:'#searchResultsGallery li[data-id], #searchResultsLargeGallery li[data-id]',adContainerSelector:'#searchResultsGallery, #searchResultsLargeGallery',imgSelector:'img.large-thumbnail',titleSelector:'a.vitrin-title',badgeContainer:e=>e,priceCell:e=>e.closest('li[data-id]')}};let currentStrategy=null;function detectViewStrategy(){return document.querySelector('#searchResultsTable')?viewStrategies.list:document.querySelector('#searchResultsGallery')||document.querySelector('#searchResultsLargeGallery')?viewStrategies.gallery:null}

// --- Global State ---
let hoverTimer=null,activeAdRow=null,adContainerObserver=null,observedAdContainer=null;const observerConfig={childList:!0,subtree:!0,attributes:!0,attributeFilter:["class"]};let sharedTooltip=null;

// --- Style Injection ---
function injectStyles(){const e='sahi-styles';if(document.getElementById(e))return;const t=document.createElement('style');t.id=e,t.textContent="\n.sahi-temiz-border{border:4px solid #2ecc71!important}.sahi-degisen-border{border:4px solid #ff5e39!important}.sahi-boyali-border{border:4px solid #4083c9!important}.sahi-lokal-border{border:4px solid #fe9546!important}.sahi-badge{position:absolute!important;top:1px!important;left:1px!important;color:#fff!important;padding:3px 6px!important;font-size:11px!important;font-weight:700!important;border-radius:4px!important;z-index:100!important;display:block!important;text-shadow:1px 1px 2px rgba(0,0,0,.5)!important}.sahi-badge-temiz{background-color:#2ecc71!important}.sahi-badge-degisen{background-color:#ff5e39!important}.sahi-badge-boyali{background-color:#4083c9!important}.sahi-badge-lokal{background-color:#fe9546!important}.sahi-custom-tooltip{display:none;position:fixed;background:#222;color:#fff;padding:5px 8px;border-radius:4px;font-size:12px;z-index:100001;pointer-events:none}",document.head.appendChild(t)}
injectStyles();

// Tooltip
function createSharedTooltip(){if(document.querySelector('.sahi-custom-tooltip'))return;sharedTooltip=document.createElement('div'),sharedTooltip.className='sahi-custom-tooltip',document.body.appendChild(sharedTooltip),document.addEventListener('mousemove',e=>{'block'===sharedTooltip.style.display&&(sharedTooltip.style.left=e.clientX+15+'px',sharedTooltip.style.top=e.clientY+15+'px')})}

// State & events
let removeHiddenAdsState=!0,isHoverPreviewEnabled=!0;chrome.storage.sync.get(['removeHiddenAds','isHoverEnabled'],e=>{removeHiddenAdsState=!1!==e.removeHiddenAds,isHoverPreviewEnabled=!1!==e.isHoverEnabled,currentStrategy&&document.querySelectorAll(currentStrategy.adRowSelector).forEach(applyRowVisibility)});chrome.runtime.onMessage.addListener(e=>{'toggleRemoveHidden'===e.action?(removeHiddenAdsState=e.remove,currentStrategy&&document.querySelectorAll(currentStrategy.adRowSelector).forEach(applyRowVisibility)):'toggleHover'===e.action&&(isHoverPreviewEnabled=e.enabled)});

function initialize(){if(!currentStrategy||!chrome.runtime?.id)return;chrome.storage.local.get(['damagedAds','cleanAds'],e=>{if(chrome.runtime.lastError)return;document.querySelectorAll(currentStrategy.adRowSelector).forEach(processAdRow)})}

function initEventListeners(){if(!currentStrategy)return;const e=document.querySelector(currentStrategy.adContainerSelector);if(!e)return;e.addEventListener('mouseenter',t=>{if(!isHoverPreviewEnabled)return;const o=t.target.closest(currentStrategy.adRowSelector);if(!o)return;clearHoverState(),activeAdRow=o;const r=o.querySelector(currentStrategy.titleSelector);if(!r)return;const n=r.href;if(!n)return;const a=createPopup(o),d=o.dataset.id,c=`popupCache_${d}`;if(!chrome.runtime?.id)return;chrome.storage.local.get(c,i=>{if(chrome.runtime.lastError)return;const l=i[c];l&&Date.now()-l.timestamp<36e5?displayPopup(a,l.data):isHoverPreviewEnabled?hoverTimer=setTimeout(()=>loadPopupData(a,n,o),800):a.innerHTML='<div>Önizleme kapalı</div>'})},!0),e.addEventListener('mouseleave',t=>{(!t.relatedTarget||!e.contains(t.relatedTarget))&&clearHoverState()},!0)}

function clearHoverState(){hoverTimer&&clearTimeout(hoverTimer),hoverTimer=null;const e=document.querySelector('.sahibinden-popup');e&&e.remove(),activeAdRow=null}
function createPopup(e){clearHoverState();const t=document.createElement('div');t.className='sahibinden-popup';const o=e.getBoundingClientRect();return t.style.cssText=`position:fixed;background:#f0f0f0;border:1px solid #ccc;border-radius:8px;box-shadow:0 4px 12px rgba(0,0,0,.2);z-index:100001;width:100px;height:100px;top:${o.top}px;left:${o.left-105}px;display:flex;align-items:center;justify-content:center;`,t.innerHTML='<div>Yükleniyor...</div>',document.body.appendChild(t),t}
function displayPopup(e,t){const{damageHTML:o,styles:r}=t;e.innerHTML='',e.style.width='100px',e.style.height='120px',e.style.overflow='hidden';const n=document.createElement('iframe');n.style.cssText='border:none;width:100%;height:100%;',e.appendChild(n),setTimeout(()=>{const e=n.contentDocument;e?(e.open(),e.write(`<html><head>${r}</head><body style="margin:0;padding:0;overflow:hidden;transform:scale(0.31);transform-origin:top left;">${o}</body></html>`),e.close()):n.parentNode&&(n.parentNode.innerHTML='<div>İçerik yüklenemedi.</div>')},0)}
function loadPopupData(e,t,o){if(!document.body.contains(e))return;fetch(t,{credentials:'include'}).then(e=>{if(!e.ok)throw new Error('Ağ hatası: '+e.status);return e.text()}).then(t=>{if(!document.body.contains(e))return;const r=new DOMParser,n=r.parseFromString(t,'text/html'),a=o.dataset.id,d=n.querySelectorAll('.car-parts .changed-new').length,c=n.querySelectorAll('.car-parts .painted-new').length,i=n.querySelectorAll('.car-parts .localpainted-new').length,l={degisen:d,boyali:c,lokal:i};if(!chrome.runtime?.id)return;d>0||c>0||i>0?(markAdWithDetailedDamage(o,l),a&&chrome.runtime.sendMessage({action:'saveDamagedAd',adId:a,damageDetails:l})):n.querySelector('.car-parts')&&(markAdAsClean(o),a&&chrome.runtime.sendMessage({action:'saveCleanAd',adId:a}));const s=n.querySelector('.damage-area');if(s){const t=s.cloneNode(!0);t.querySelector('.car-damage-info')&&t.querySelector('.car-damage-info').remove();const o=Array.from(n.querySelectorAll('style, link[rel="stylesheet"]')).map(e=>e.outerHTML).join(''),r={data:{damageHTML:t.outerHTML,styles:o},timestamp:Date.now()};a&&chrome.storage.local.set({[`popupCache_${a}`]:r},()=>{}),displayPopup(e,r.data)}else e.innerHTML='<div>Hasar bilgisi yok.</div>'}).catch(()=>{e&&e.parentNode&&(e.innerHTML='<div>Hata.</div>')})}
function markAdWithDetailedDamage(e,t){if(!currentStrategy)return;const{degisen:o,boyali:r,lokal:n}=t,a=e.querySelector(currentStrategy.imgSelector);let d=e.querySelector('.sahi-badge');a&&(a.className=a.className.replace(/sahi-.*?-border/g,'')),d&&d.remove();const c=currentStrategy.badgeContainer(e);if(!c)return;c.style.position='relative',d=document.createElement('div'),d.className='sahi-badge',c.appendChild(d);let i='',l='',s='';let g=0;o>0&&g++,r>0&&g++,n>0&&g++,g>1&&(d.title='',d.addEventListener('mouseover',()=>{sharedTooltip&&(sharedTooltip.innerHTML=`Değişen: ${o}, Boyalı: ${r}, Lokal: ${n}`,sharedTooltip.style.display='block')}),d.addEventListener('mouseout',()=>{sharedTooltip&&(sharedTooltip.style.display='none')})),o>0?(i=`Değişen: ${o}`+(r+n>0?` (+${r+n})`:''),l='sahi-badge-degisen',s='sahi-degisen-border'):r>0?(i=`Boyalı: ${r}`+(n>0?` (+${n})`:''),l='sahi-badge-boyali',s='sahi-boyali-border'):n>0&&(i=`Lokal: ${n}`,l='sahi-badge-lokal',s='sahi-lokal-border');d.textContent=i,d.classList.add(l),a&&s&&a.classList.add(s)}
function markAdAsClean(e){if(!currentStrategy)return;const t=e.querySelector(currentStrategy.imgSelector);t&&(t.className=t.className.replace(/sahi-.*?-border/g,''),t.classList.add('sahi-temiz-border'));let o=e.querySelector('.sahi-badge');o&&o.remove();const r=currentStrategy.badgeContainer(e);if(!r)return;r.style.position='relative',o=document.createElement('div'),o.className='sahi-badge sahi-badge-temiz',o.textContent='Temiz',r.appendChild(o)}
function applyRowVisibility(e){e.classList.contains('searchResultsIgnored')?removeHiddenAdsState?e.style.display='none':e.style.display='list'===currentStrategy.id?'table-row':'block':e.style.display=''}
function processAdRow(e){applyRowVisibility(e);const t=e.dataset.id;t&&chrome.runtime?.id&&chrome.storage.local.get(['damagedAds','cleanAds'],o=>{if(chrome.runtime.lastError)return;const r=(o.damagedAds||{})[t];r?markAdWithDetailedDamage(e,r):(o.cleanAds||{})[t]&&markAdAsClean(e)})}
function observeAdContainer(e){observedAdContainer=e,adContainerObserver=new MutationObserver(t=>{for(const o of t)if('childList'===o.type)for(const t of o.addedNodes)t.nodeType===Node.ELEMENT_NODE&&(t.matches(currentStrategy.adRowSelector)?processAdRow(t):t.querySelectorAll(currentStrategy.adRowSelector).forEach(processAdRow));else"attributes"===o.type&&'class'===o.attributeName&&o.target&&o.target.matches(currentStrategy.adRowSelector)&&setTimeout(()=>{document.body.contains(o.target)&&applyRowVisibility(o.target)},50)}),adContainerObserver.observe(observedAdContainer,observerConfig)}
function runInitialization(){const e=detectViewStrategy();if(!e)return;const t=document.querySelector(e.adContainerSelector);if(currentStrategy&&currentStrategy.id===e.id&&t&&'true'===t.dataset.sahiInitialized)return;currentStrategy=e,t&&(t.dataset.sahiInitialized='true',initialize(),initEventListeners(),createSharedTooltip(),observeAdContainer(t))}
const bodyObserver=new MutationObserver(()=>{observedAdContainer&&!document.body.contains(observedAdContainer)&&(adContainerObserver&&adContainerObserver.disconnect(),observedAdContainer.dataset&&observedAdContainer.removeAttribute('data-sahi-initialized'),observedAdContainer=null,adContainerObserver=null,currentStrategy=null),runInitialization()});
bodyObserver.observe(document.body,{childList:!0,subtree:!0});
setTimeout(runInitialization,500);


